<?= $this->doctype() . "\n"; ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php myHeadLink($this->baseUrl());?>
        <?php myHeadScript($this->baseUrl());?>
        <?php echo $this->headTitle() . "\n" ?>
        <?php echo $this->headMeta() . "\n" ?>
        <?php echo $this->headLink() . "\n" ?>   
        <?php echo $this->headScript() . "\n" ?>

            
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    </head>
    <body>              
        
        <!-- Subhead -->
        <header class="jumbotron subhead" id="overview">
          <div class="container">
            <h1>Base CSS</h1>
            <p class="lead">Fundamental HTML elements styled and enhanced with extensible classes.</p>
          </div>
        </header>

      <div class="container">

        <?php if (isset($this->messages)): ?>
          <?php echo $this->partial('partials/messenger.phtml', array('messages' => $this->messages)); ?>
        <?php endif ?>

        <?php echo $this->layout()->content ?>

      </div>
        
    </body>
</html>

<?php 
 function myHeadLink($baseUrl) {
    $host = $baseUrl;
    $headLinkHelper = new Zend_View_Helper_HeadLink();
    $headLinkHelper
            ->setStylesheet("//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.no-icons.min.css")
            //->appendStylesheet($host ."/css2/fontello.css")
            //->appendStylesheet($host ."/css2/animation.css")
            //->appendStylesheet($host ."/css2/flat/green.css")
            //->appendStylesheet($host ."/css2/flat/blue.css")
            //->appendStylesheet($host ."/css2/square/blue.css")
            ->appendStylesheet($host ."/css2/alertify.core.css")
            ->appendStylesheet($host ."/css2/alertify.default.css")
            ->appendStylesheet($host ."/css2/flat.css")
            //->appendStylesheet($host ."/css2/app.css")
    ;
  }
  
  function myHeadScript($baseUrl) {

    $host = $baseUrl;
    $headScriptHelper = new Zend_View_Helper_HeadScript();
    $headScriptHelper
            //->appendFile("//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js", "text/javascript")
            //->appendFile("//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js", "text/javascript")
            //->appendFile($host ."/js2/jquery.livequery.min.js", "text/javascript")
            //->appendFile($host ."/js2/moment.js", "text/javascript")
            //->appendFile($host ."/js2/response.js", "text/javascript")
            //->appendFile($host ."/js2/jquery.icheck.min.js", "text/javascript")
            //->appendFile($host ."/js2/jquery.mask.min.js", "text/javascript")
            //->appendFile($host ."/js2/jquery.cookie.js", "text/javascript")
            ->appendFile($host ."/js2/alertify.js", "text/javascript")
            //->appendFile($host ."/js2/jquery.number.min.js", "text/javascript")
            //->appendFile($host ."/js2/autoNumeric.js", "text/javascript")
            //->appendFile($host ."/js2/bootstrap-select.min.js", "text/javascript")
            //->appendFile($host ."/js2/select2.min.js", "text/javascript")//                
            //->appendFile($host ."/js2/app.js", "text/javascript")
    ;
  }

;?>