<?= $this->doctype() . "\n"; ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php myHeadLink($this->baseUrl());?>
        <?php myHeadScript($this->baseUrl());?>
        <?php echo $this->headTitle() . "\n" ?>
        <?php echo $this->headMeta() . "\n" ?>
        <?php echo $this->headLink() . "\n" ?>   
        <?php echo $this->headScript() . "\n" ?>

            
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        
          <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="assets/js/html5shiv.js"></script>
        <![endif]-->

    </head>
    <body>              

      <div class="container">
        
        <?php if (isset($this->messages)): ?>
          <?php echo $this->partial('partials/messenger.phtml', array('messages' => $this->messages)); ?>
        <?php endif ?>

        <?php echo $this->layout()->content ?>
      </div>
        


        
    </body>
</html>
<?php 
 function myHeadLink($baseUrl) {
    $host = $baseUrl;
    $headLinkHelper = new Zend_View_Helper_HeadLink();
    $headLinkHelper
            ->setStylesheet($host ."/css/bootstrap.css")
            ->appendStylesheet($host ."/css/bootstrap-responsive.min.css")
            ->appendStylesheet($host ."/css/flat.css")
            ->appendStylesheet($host ."/css/color-palette.css")
            ->appendStylesheet($host ."/css/color-palette-full.css")
            ->appendStylesheet($host ."/css/docs.css")
            ->appendStylesheet("http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic|Open+Sans:300italic,400italic,600italic,700italic,800italic,400,800,700,600,300'")
            ->appendStylesheet($host ."/css2/app.css")
    ;
  }

  function myHeadScript($baseUrl) {

    $host = $baseUrl;
    $headScriptHelper = new Zend_View_Helper_HeadScript();
    $headScriptHelper
            //->appendFile("//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js", "text/javascript")
            //->appendFile("//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js", "text/javascript")
            //->appendFile($host ."/js/bootstrap.min.js", "text/javascript")
            //->appendFile($host ."/js/flat.js", "text/javascript")
            ->appendFile($host ."/js2/alertify.js", "text/javascript")            
            //->appendFile($host ."/js2/app.js", "text/javascript")
    ;
  }

;?>